---
# Template to set build status in Bitbucket (aka sourcecode)
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: git-clone-
spec:
  entrypoint: git-clone
  serviceAccountName: argo-workflows-sa
  imagePullSecrets:
    - name: jnj-artifactory
  templates:
    - name: git-checkout
      inputs:
        artifacts:
          - name: source
            path: /src
            mode: 0755
            recurseMode: true
            git:
              repo: "https://github.com/MatthiasRoels/argo-examples.git"
              singleBranch: true
              branch: "test"
              revision: "86d78983d2d789e19eb91734e1a8833cb2139fc8"
      script:
        image: jnj.artifactrepo.jnj.com/busybox:latest
        command: ["bash"]
        source: |
          ls -lah
        workingDir: /src
