---
# Example Workflow to test git artifact
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: git-clone-
spec:
  entrypoint: git-clone
  serviceAccountName: argo-workflows-sa
  imagePullSecrets:
    - name: jnj-artifactory
  templates:
    - name: git-clone
      inputs:
        artifacts:
          - name: source
            path: /src
            mode: 0755
            recurseMode: true
            git:
              repo: "https://github.com/MatthiasRoels/argo-examples.git"
              revision: "25f19eaf802d287f104c06c6a885c29f0b770f92"
      script:
        image: jnj.artifactrepo.jnj.com/busybox:latest
        command: ["sh"]
        source: |
          ls -lah
        workingDir: /src
